
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action ViewAction;

	private global::Gtk.Action BookmarksAction;

	private global::Gtk.Action MainWindowAddMyLabelAction;

	private global::Gtk.Action NewTabAction;

	private global::Gtk.Action PrintAction;

	private global::Gtk.Action OpenFileAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action EditAction1;

	private global::Gtk.Action ViewAction1;

	private global::Gtk.Action FavouritesAction;

	private global::Gtk.Action OpenFileAction1;

	private global::Gtk.Action HomePageAction;

	private global::Gtk.Action PrintAction1;

	private global::Gtk.Action BackAction;

	private global::Gtk.Action ForwardAction;

	private global::Gtk.Action FullHistoryAction;

	private global::Gtk.Action HistoryAction;

	private global::Gtk.Action HomePageAction1;

	private global::Gtk.Action BackAction1;

	private global::Gtk.Action ForwardAction1;

	private global::Gtk.Action ViewHistoryAction;

	private global::Gtk.Action Action;

	private global::Gtk.Action addToFavsLabel;

	private global::Gtk.Action ViewAllFavouritesAction;

	private global::Gtk.Action HomeAction;

	private global::Gtk.Action SetAsHomePageAction;

	private global::Gtk.Action NewWindowAction;

	private global::Gtk.Action NewTabAction1;

	private global::Gtk.Action ShareAction;

	private global::Gtk.Action UndoAction;

	private global::Gtk.Action RedoAction;

	private global::Gtk.Action CutAction;

	private global::Gtk.Action CopyAction;

	private global::Gtk.Action PasteAction;

	private global::Gtk.Action ZoomInAction;

	private global::Gtk.Action ZoomOutAction;

	private global::Gtk.Action EditHomePageURLAction;

	private global::Gtk.Action ClearHistoryAction;

	private global::Gtk.VBox vBox;

	private global::Gtk.MenuBar menuBar;

	private global::Gtk.VBox vbox14;

	private global::Gtk.Label title;

	private global::Gtk.HBox hbox4;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button backButton;

	private global::Gtk.Button button7;

	private global::Gtk.Button Refresh;

	private global::Gtk.Entry urlInput;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Label label11;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.ViewAction = new global::Gtk.Action("ViewAction", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction, null);
		this.BookmarksAction = new global::Gtk.Action("BookmarksAction", global::Mono.Unix.Catalog.GetString("Bookmarks"), null, null);
		this.BookmarksAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Bookmarks");
		w1.Add(this.BookmarksAction, null);
		this.MainWindowAddMyLabelAction = new global::Gtk.Action("MainWindowAddMyLabelAction", global::Mono.Unix.Catalog.GetString("            mainWindow.Add(myLabel)"), null, null);
		this.MainWindowAddMyLabelAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open File..");
		w1.Add(this.MainWindowAddMyLabelAction, null);
		this.NewTabAction = new global::Gtk.Action("NewTabAction", global::Mono.Unix.Catalog.GetString("New Tab"), null, null);
		this.NewTabAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New Tab");
		w1.Add(this.NewTabAction, null);
		this.PrintAction = new global::Gtk.Action("PrintAction", global::Mono.Unix.Catalog.GetString("Print"), null, null);
		this.PrintAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Print");
		w1.Add(this.PrintAction, null);
		this.OpenFileAction = new global::Gtk.Action("OpenFileAction", global::Mono.Unix.Catalog.GetString("Open File.."), null, null);
		this.OpenFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open File..");
		w1.Add(this.OpenFileAction, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction1, null);
		this.EditAction1 = new global::Gtk.Action("EditAction1", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction1, null);
		this.ViewAction1 = new global::Gtk.Action("ViewAction1", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction1, null);
		this.FavouritesAction = new global::Gtk.Action("FavouritesAction", global::Mono.Unix.Catalog.GetString("Favourites"), null, null);
		this.FavouritesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Bookmarks");
		w1.Add(this.FavouritesAction, null);
		this.OpenFileAction1 = new global::Gtk.Action("OpenFileAction1", global::Mono.Unix.Catalog.GetString("Open File.."), null, null);
		this.OpenFileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Open File..");
		w1.Add(this.OpenFileAction1, null);
		this.HomePageAction = new global::Gtk.Action("HomePageAction", global::Mono.Unix.Catalog.GetString("Home Page"), null, null);
		this.HomePageAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Home Page");
		w1.Add(this.HomePageAction, null);
		this.PrintAction1 = new global::Gtk.Action("PrintAction1", global::Mono.Unix.Catalog.GetString("Print"), null, null);
		this.PrintAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Print");
		w1.Add(this.PrintAction1, null);
		this.BackAction = new global::Gtk.Action("BackAction", global::Mono.Unix.Catalog.GetString("Back"), null, null);
		this.BackAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Back");
		w1.Add(this.BackAction, null);
		this.ForwardAction = new global::Gtk.Action("ForwardAction", global::Mono.Unix.Catalog.GetString("Forward"), null, null);
		this.ForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Forward");
		w1.Add(this.ForwardAction, null);
		this.FullHistoryAction = new global::Gtk.Action("FullHistoryAction", global::Mono.Unix.Catalog.GetString("Full History"), null, null);
		this.FullHistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Full History");
		w1.Add(this.FullHistoryAction, null);
		this.HistoryAction = new global::Gtk.Action("HistoryAction", global::Mono.Unix.Catalog.GetString("History"), null, null);
		this.HistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("History");
		w1.Add(this.HistoryAction, null);
		this.HomePageAction1 = new global::Gtk.Action("HomePageAction1", global::Mono.Unix.Catalog.GetString("Home Page"), null, null);
		this.HomePageAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Home Page");
		w1.Add(this.HomePageAction1, null);
		this.BackAction1 = new global::Gtk.Action("BackAction1", global::Mono.Unix.Catalog.GetString("Back"), null, null);
		this.BackAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Back");
		w1.Add(this.BackAction1, null);
		this.ForwardAction1 = new global::Gtk.Action("ForwardAction1", global::Mono.Unix.Catalog.GetString("Forward"), null, null);
		this.ForwardAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Forward");
		w1.Add(this.ForwardAction1, null);
		this.ViewHistoryAction = new global::Gtk.Action("ViewHistoryAction", global::Mono.Unix.Catalog.GetString("View History"), null, null);
		this.ViewHistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Full History");
		w1.Add(this.ViewHistoryAction, null);
		this.Action = new global::Gtk.Action("Action", null, null, null);
		w1.Add(this.Action, null);
		this.addToFavsLabel = new global::Gtk.Action("addToFavsLabel", global::Mono.Unix.Catalog.GetString("Add to Favourites"), null, "gtk-about");
		this.addToFavsLabel.ShortLabel = global::Mono.Unix.Catalog.GetString("Add to Favourites");
		w1.Add(this.addToFavsLabel, null);
		this.ViewAllFavouritesAction = new global::Gtk.Action("ViewAllFavouritesAction", global::Mono.Unix.Catalog.GetString("View All Favourites"), null, null);
		this.ViewAllFavouritesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View All Favourites");
		w1.Add(this.ViewAllFavouritesAction, null);
		this.HomeAction = new global::Gtk.Action("HomeAction", global::Mono.Unix.Catalog.GetString("Home"), null, null);
		this.HomeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Home");
		w1.Add(this.HomeAction, null);
		this.SetAsHomePageAction = new global::Gtk.Action("SetAsHomePageAction", global::Mono.Unix.Catalog.GetString("Set As Home Page"), null, null);
		this.SetAsHomePageAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Set As Home Page");
		w1.Add(this.SetAsHomePageAction, null);
		this.NewWindowAction = new global::Gtk.Action("NewWindowAction", global::Mono.Unix.Catalog.GetString("New Window"), null, null);
		this.NewWindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New Window");
		w1.Add(this.NewWindowAction, null);
		this.NewTabAction1 = new global::Gtk.Action("NewTabAction1", global::Mono.Unix.Catalog.GetString("New Tab"), null, null);
		this.NewTabAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("New Tab");
		w1.Add(this.NewTabAction1, null);
		this.ShareAction = new global::Gtk.Action("ShareAction", global::Mono.Unix.Catalog.GetString("Share"), null, null);
		this.ShareAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Share");
		w1.Add(this.ShareAction, null);
		this.UndoAction = new global::Gtk.Action("UndoAction", global::Mono.Unix.Catalog.GetString("Undo"), null, null);
		this.UndoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Undo");
		w1.Add(this.UndoAction, null);
		this.RedoAction = new global::Gtk.Action("RedoAction", global::Mono.Unix.Catalog.GetString("Redo"), null, null);
		this.RedoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Redo");
		w1.Add(this.RedoAction, null);
		this.CutAction = new global::Gtk.Action("CutAction", global::Mono.Unix.Catalog.GetString("Cut"), null, null);
		this.CutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cut");
		w1.Add(this.CutAction, null);
		this.CopyAction = new global::Gtk.Action("CopyAction", global::Mono.Unix.Catalog.GetString("Copy"), null, null);
		this.CopyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copy");
		w1.Add(this.CopyAction, null);
		this.PasteAction = new global::Gtk.Action("PasteAction", global::Mono.Unix.Catalog.GetString("Paste"), null, null);
		this.PasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Paste");
		w1.Add(this.PasteAction, null);
		this.ZoomInAction = new global::Gtk.Action("ZoomInAction", global::Mono.Unix.Catalog.GetString("Zoom In"), null, null);
		this.ZoomInAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Zoom In");
		w1.Add(this.ZoomInAction, null);
		this.ZoomOutAction = new global::Gtk.Action("ZoomOutAction", global::Mono.Unix.Catalog.GetString("Zoom Out"), null, null);
		this.ZoomOutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Zoom Out");
		w1.Add(this.ZoomOutAction, null);
		this.EditHomePageURLAction = new global::Gtk.Action("EditHomePageURLAction", global::Mono.Unix.Catalog.GetString("Edit Home Page URL"), null, null);
		this.EditHomePageURLAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit Home Page URL");
		w1.Add(this.EditHomePageURLAction, null);
		this.ClearHistoryAction = new global::Gtk.Action("ClearHistoryAction", global::Mono.Unix.Catalog.GetString("Clear History"), null, null);
		this.ClearHistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Clear History");
		w1.Add(this.ClearHistoryAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBox = new global::Gtk.VBox();
		this.vBox.Name = "vBox";
		this.vBox.Spacing = 6;
		// Container child vBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menuBar\'><menu name=\'FileAction1\' action=\'FileAction1\'><menuit" +
				"em name=\'NewWindowAction\' action=\'NewWindowAction\'/><menuitem name=\'NewTabAction" +
				"1\' action=\'NewTabAction1\'/><menuitem name=\'OpenFileAction1\' action=\'OpenFileActi" +
				"on1\'/><menuitem name=\'PrintAction1\' action=\'PrintAction1\'/><menuitem name=\'Share" +
				"Action\' action=\'ShareAction\'/></menu><menu name=\'EditAction1\' action=\'EditAction" +
				"1\'><menuitem name=\'UndoAction\' action=\'UndoAction\'/><menuitem name=\'RedoAction\' " +
				"action=\'RedoAction\'/><menuitem name=\'CutAction\' action=\'CutAction\'/><menuitem na" +
				"me=\'CopyAction\' action=\'CopyAction\'/><menuitem name=\'PasteAction\' action=\'PasteA" +
				"ction\'/></menu><menu name=\'ViewAction1\' action=\'ViewAction1\'><menuitem name=\'Zoo" +
				"mInAction\' action=\'ZoomInAction\'/><menuitem name=\'ZoomOutAction\' action=\'ZoomOut" +
				"Action\'/></menu><menu name=\'FavouritesAction\' action=\'FavouritesAction\'><menuite" +
				"m name=\'addToFavsLabel\' action=\'addToFavsLabel\'/><menuitem name=\'ViewAllFavourit" +
				"esAction\' action=\'ViewAllFavouritesAction\'/></menu><menu name=\'HistoryAction\' ac" +
				"tion=\'HistoryAction\'><menuitem name=\'BackAction1\' action=\'BackAction1\'/><menuite" +
				"m name=\'ForwardAction1\' action=\'ForwardAction1\'/><menuitem name=\'ViewHistoryActi" +
				"on\' action=\'ViewHistoryAction\'/><menuitem name=\'ClearHistoryAction\' action=\'Clea" +
				"rHistoryAction\'/></menu><menu name=\'HomeAction\' action=\'HomeAction\'><menuitem na" +
				"me=\'HomePageAction1\' action=\'HomePageAction1\'/><menuitem name=\'SetAsHomePageActi" +
				"on\' action=\'SetAsHomePageAction\'/><menuitem name=\'EditHomePageURLAction\' action=" +
				"\'EditHomePageURLAction\'/></menu><menu name=\'Action\' action=\'Action\'/></menubar><" +
				"/ui>");
		this.menuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menuBar")));
		this.menuBar.Name = "menuBar";
		this.vBox.Add(this.menuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vBox[this.menuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		this.vbox14.BorderWidth = ((uint)(3));
		// Container child vbox14.Gtk.Box+BoxChild
		this.title = new global::Gtk.Label();
		this.title.Name = "title";
		this.title.LabelProp = global::Mono.Unix.Catalog.GetString("Page Title");
		this.vbox14.Add(this.title);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.title]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.backButton = new global::Gtk.Button();
		this.backButton.CanFocus = true;
		this.backButton.Name = "backButton";
		this.backButton.UseUnderline = true;
		this.backButton.Label = global::Mono.Unix.Catalog.GetString("Back");
		this.hbox6.Add(this.backButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.backButton]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Forward");
		this.hbox6.Add(this.button7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.button7]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Refresh = new global::Gtk.Button();
		this.Refresh.CanFocus = true;
		this.Refresh.Name = "Refresh";
		this.Refresh.UseUnderline = true;
		this.Refresh.Label = global::Mono.Unix.Catalog.GetString("Refresh");
		this.hbox6.Add(this.Refresh);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Refresh]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.hbox4.Add(this.hbox6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox6]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.urlInput = new global::Gtk.Entry();
		this.urlInput.CanFocus = true;
		this.urlInput.Name = "urlInput";
		this.urlInput.IsEditable = true;
		this.urlInput.InvisibleChar = '●';
		this.hbox4.Add(this.urlInput);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.urlInput]));
		w8.Position = 1;
		this.vbox14.Add(this.hbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox4]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.vBox.Add(this.vbox14);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vBox[this.vbox14]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("statusCode");
		this.vBox.Add(this.label1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vBox[this.label1]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w12 = new global::Gtk.Viewport();
		w12.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("label11");
		w12.Add(this.label11);
		this.scrolledwindow1.Add(w12);
		this.vBox.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vBox[this.scrolledwindow1]));
		w15.Position = 3;
		this.Add(this.vBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 547;
		this.DefaultHeight = 374;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.onKeyPress);
		this.FavouritesAction.Activated += new global::System.EventHandler(this.onFavsActive);
		this.HomePageAction1.Activated += new global::System.EventHandler(this.goToHomePage);
		this.BackAction1.Activated += new global::System.EventHandler(this.onClickBackButton);
		this.ForwardAction1.Activated += new global::System.EventHandler(this.onClickForwardButton);
		this.ViewHistoryAction.Activated += new global::System.EventHandler(this.onClickFullHistory);
		this.addToFavsLabel.Activated += new global::System.EventHandler(this.onClickFav);
		this.ViewAllFavouritesAction.Activated += new global::System.EventHandler(this.onClickAllFavs);
		this.SetAsHomePageAction.Activated += new global::System.EventHandler(this.setHomePage);
		this.EditHomePageURLAction.Activated += new global::System.EventHandler(this.onClickEditHome);
		this.ClearHistoryAction.Activated += new global::System.EventHandler(this.onClickClearHistory);
		this.backButton.Clicked += new global::System.EventHandler(this.onClickBackButton);
		this.button7.Clicked += new global::System.EventHandler(this.onClickForwardButton);
		this.Refresh.Clicked += new global::System.EventHandler(this.onClickRefresh);
		this.urlInput.Activated += new global::System.EventHandler(this.onUrlEnter);
	}
}
